Aggiunta IO nella sezione Piattaforme
publiccodeyml/publiccode.yml pull request #139
Opened 2022-03-21 16:37 UTC by mspasiano

2022-03-28 10:09 UTC, bfabio requested changes
So it is coherent with #141

2022-03-28 10:09 UTC, bfabio commented on docs/it/schema.it.rst
> +Se presente e impostato a ``yes``, il software si interfaccia con `IO - l'app dei servizi pubblici <https://io.italia.it/>`__.
```suggestion
Se presente e impostato a ``true``, il software si interfaccia con `IO - l'app dei servizi pubblici <https://io.italia.it/>`__.
```

2022-03-28 10:10 UTC, bfabio commented
Thanks for the PR @mspasiano, can you please rebase it on main so that we can get the preview?

2022-03-28 10:11 UTC, bfabio commented
@yaml-9000 national-section ruphy
@yaml-9000 minor-change

2022-03-28 10:11 UTC, yaml-9000 commented
<!-- ##bot-national-section-marker## "ruphy" -->

This is now marked as a national section change to the Standard and it will require the approval of the Steering Committee member representing the Country (@ruphy) and at least 50% approve votes.

[National section rules](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#country-specific-sections)

cc @ruphy @ruphy @publiccodeyml/steering-committee

<!-- ##bot-comment-marker## -->
<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

2022-03-28 10:11 UTC, yaml-9000 commented
Thanks for your contribution :pray:

This is now marked as a [`minor-change` proposal to the standard](https://github.com/publiccodeyml/publiccode.yml/labels/standard-minor-change),
this means that old versions of `publiccode.yml` will still be valid with this change.

Example of minor changes are additions of new keys or making keys optional.

The Chair will eventually pick up this proposal and start the voting procedure using `@yaml-9000 vote-start`

cc @ruphy @publiccodeyml/steering-committee

<!-- ##bot-comment-marker## -->
<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

2022-04-13 13:03 UTC, ruphy commented
@yaml-9000 vote-start

2022-04-13 13:03 UTC, yaml-9000 commented
<!-- ##bot-voting-marker## -->
**Voting is now open on this proposal!**

If you are a member of the [Steering Committee](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md#steering-committee-publiccodeymlsteering-committee) you can now vote!

The polls will stay open for 14 days, until **Wed, 27 Apr 2022 13:03:42 GMT**.
At the end of that period the Chair (@ruphy) will mark the voting period as over using `@yaml-9000 vote-end`

Leave a :+1: (thumbs up) **on this comment** to accept the proposal or a :-1: (thumbs down) to reject it.

cc @publiccodeyml/steering-committee

<!-- ##bot-comment-marker## -->
<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

2022-04-29 14:50 UTC, yaml-9000 commented
# Vote results

The results of [the vote](https:&#x2F;&#x2F;github.com&#x2F;publiccodeyml&#x2F;publiccode.yml&#x2F;pull&#x2F;139#issuecomment-1098024598) are:

|Vote|Members|Votes count|Percentage|
|-|-|-|-|
|:+1: Approve | @ruphy @bzg   | 2   | 100.0%   |
|:-1: Reject  |  | 0 | - |



**Proposal approved** :+1:

This proposal is now ready to be merged and get released with a new version of the standard.
      

cc @ruphy @publiccodeyml/maintainers


<details>
  <summary><sub>Details<sub></summary>
  <br>
  <p>
    <strong>National section vote</strong>: approve vote by ruphy required and at least <strong>50%</strong> approve votes
  </p>
  <p>
    The following users voted (includes non-members of the steering committee):
  </p>

  - <strong>mspasiano</strong> voted :+1:

- <strong>ruphy</strong> voted :+1:

- <strong>bzg</strong> voted :+1:
</details>

<!-- ##bot-comment-marker## -->
<sub>[:page_facing_up: Voting procedure](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md#voting) | [:page_facing_up: Working Group Charter](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/charter.md) | [:robot: bot commands](https://github.com/publiccodeyml/bot#commands)</sub>

2022-05-02 08:23 UTC, bfabio approved these changes

2022-05-02 08:24 UTC, merged